### ISSUE TITLE
Problem with Executing Algorithms - Docker - TimeEval-algorithms

### ISSUE THREAD

**Issue by kalifou** [kplabs-pl/ESA-ADB#4]
Hello,

I am currently having issues with executing and benchmarking algorithms on your repo.
After installing the repo and I have decided to follow the steps in the _ESA-TimeEval-algorithms_ guiding page: 
_https://github.com/kplabs-pl/ESA-ADB/tree/main/TimeEval-algorithms_

The issue is related to the containerization of the algorithms.
It occurs when I use the commands in section _3. Train your algorithm_ or _4. Execute your algorithm_ (after building the individual images).
It also occurs when I run the test.sh script: bash test.sh algorithm {train / execute}
This occurs for all, e.g lof, pcc, copod, knn...

> (docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": permission denied: unknown)

However, this does not occur then doing the same experiments on the original repository of TimeEval-algorithms (same machine and docker setting, same commands, different repo).

Would you have pointers on how to fix this issue ?
I initially thought it had to do with my docker installation...which now cleared after the comparison .

Many thanks
René

**Comment by Kotrix** [comment]
Hi, adjusting permissions of the entrypoint.sh before building the Docker image should solve the problem. However, it is interesting that you do not encounter the same problem when working with the original TimeEval. I will try to investigate this problem next week.

**Comment by kalifou** [comment]
Hi,

Thank you for your reply.

Sure, regarding the permissions, I have looked a bit into it.
For instance, I looked into the Dockerfile of a target algorithm, say pcc, to see how to add missing rights to the configuration. 
(https://github.com/kplabs-pl/ESA-ADB/blob/main/TimeEval-algorithms/pcc/Dockerfile), but without success.


Example of line added: 
RUN ["chmod", "+x", "/app/algorithm.py"]
ENTRYPOINT["/app/algorithm.py"] (tried with and without previous line)
Outcome: issue not solved. 

Would you have any recommendations?

Another possible directon would be the difference in the Dockerfiles accross repositories for the algos..
For instannce, for KNN,  here is the diffs of the files, which appear at the first line, somehow related to the base image version:
```
< FROM registry.gitlab.hpi.de/akita/i/pyod-1.1.2
---
> FROM ghcr.io/timeeval/pyod:0.3.1
```

I am not sure yet how this could cause/relate to my issue.
Cheers

**Comment by robomorelli** [comment]
Hi to everyone,

I Had the same issue and I tried your last suggestion (Kotrix) and it did not work. There is a way to register to your private docker hub? Or other solutions? 

Please, we don't manage to keep our benchmark study

Thank you

**Comment by ARNAUD-25** [comment]
Hello,  

I would like to contribute to the discussion and respond on behalf of @robomorelli. I followed all the steps described in the README contained in the **TimeEval-algorithms** document. The steps, as described, were:  

- `cd 0-base-images`  
- `docker build -t registry.gitlab.hpi.de/akita/i/python3-base ./python3-base`  
- `docker build -t registry.gitlab.hpi.de/akita/i/pyod ./pyod`  
- `cd ..` to return to **timeeval-algorithms**  
- Then, I ran `docker build -t registry.gitlab.hpi.de/akita/i/iForest ./iForest` for this algorithm, and I received the following error:  

```
ERROR [internal] load metadata for registry.gitlab.hpi.de/akita/i/pyod-1.1.2:latest                   
------
 > [internal] load metadata for registry.gitlab.hpi.de/akita/i/pyod-1.1.2:latest:
------
Dockerfile:1
--------------------
   1 | >>> FROM registry.gitlab.hpi.de/akita/i/pyod-1.1.2
   2 |     
   3 |     LABEL maintainer="sebastian.schmidl@hpi.de"
--------------------
ERROR: failed to solve: registry.gitlab.hpi.de/akita/i/pyod-1.1.2: failed to resolve source metadata for registry.gitlab.hpi.de/akita/i/pyod-1.1.2:latest: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://gitlab.hpi.de/jwt/auth?scope=repository%3Aakita%2Fi%2Fpyod-1.1.2%3Apull&service=container_registry: 403 Forbidden
```

I’m not sure if I made a mistake or misunderstood the process.  

Could you please guide me? Thanks!

**Comment by Kotrix** [comment]
@ARNAUD-25 your problem is related to the fact that you built `docker build -t registry.gitlab.hpi.de/akita/i/pyod ./pyod` instead of `docker build -t registry.gitlab.hpi.de/akita/i/pyod-1.1.2 ./pyod-1.1.2`. The latter should resolve your problem.

Also, please mind that it should be `iforest` not `iForest` in your last step.

**Comment by ARNAUD-25** [comment]
Thank you very much for the clarification, and I have just completed this step. The next step concerns the usage of:

```bash
mkdir -p 2-results
docker run --rm \
    -v $(pwd)/1-data:/data:ro \
    -v $(pwd)/2-results:/results:rw \
#    -e LOCAL_UID=<current user id> \
#    -e LOCAL_GID=<current group id> \
  registry.gitlab.hpi.de/akita/i/<your_algorithm>:latest execute-algorithm '{ \
    "executionType": "execute", \
    "dataInput": "/data/dataset.csv", \
    "dataOutput": "/results/anomaly_scores.ts", \
    "modelInput": "/results/model.pkl", \
    "modelOutput": "/results/model.pkl", \
    "customParameters": {} \
  }'
```
While executing it in the `timeeval-algorithms` directory, I am following this order: first, I execute `mkdir -p 2-results`, and then I run `docker run --rm \ 
    -v $(pwd)/1-data:/data:ro \
    -v $(pwd)/2-results:/results:rw \
  registry.gitlab.hpi.de/akita/i/iforest:latest python algorithm.py '{ \
    "executionType": "execute", \
    "dataInput": "/data/dataset.csv", \
    "dataOutput": "/results/anomaly_scores.ts", \
    "modelInput": "/results/model.pkl", \
    "modelOutput": "/results/model.pkl", \
    "customParameters": {} \
  }'`
I receive the following error:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/entrypoint.sh": permission denied: unknown.
```
Could you please guide me again?

**Comment by Kotrix** [comment]
The problem with `exec: "/entrypoint.sh": permission denied: unknown.` is related to the lack of "Execute" permissions to the entrypoint.sh file. Running `chmod +x entrypoint.sh` and rebuilding the container should resolve the issue.

**Comment by ARNAUD-25** [comment]
Thank you @Kotrix, as I was able to resolve this issue thanks to your suggestion. 

I am currently encountering an error when using the data. The goal is to reproduce the results using the ESA-ADB data.  

I tried using the following Docker command in *TimeEval-algorithms*:  

```bash
docker run --rm \
    -v $(pwd)/1-data:/data:ro \
    -v $(pwd)/2-results:/results:rw \
    registry.gitlab.hpi.de/akita/i/knn:latest python algorithm.py '{ 
    "executionType": "train", 
    "dataInput": "/data/dataset.csv", 
    "dataOutput": "/results/anomaly_scores.ts", 
    "modelInput": "/results/model.pkl", 
    "modelOutput": "/results/model.pkl", 
    "customParameters": {} 
  }'
```

However, I receive the following error:  

```
Traceback (most recent call last):
  File "algorithm.py", line 147, in <module>
    config = AlgorithmArgs.from_sys_args()
  File "algorithm.py", line 32, in from_sys_args
    args: dict = json.loads(sys.argv[1])
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2).
```

Next, I ran the command: python mission1_experiments.py

I then received the following error:

```
Desktop/ESA-ADB-main/timeeval/timeeval.py:370: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  self.results = self.results.append(new_row, ignore_index=True)
```

An exception occurred during the evaluation of *Subsequence IF* on the dataset:  

```
Dataset(datasetId=('ESA-Mission1', '42_months'), dataset_type='real', training_type=<TrainingType.SEMI_SUPERVISED: 'semi-supervised'>, length=3677761, dimensions=87, contamination=0.0178164058944071, min_anomaly_length=0, median_anomaly_length=196.0, max_anomaly_length=40248, period_size=0.0, num_anomalies=11.586206896551724).
```

Error traceback:  

```
urllib3.exceptions.URLSchemeUnknown: Not supported URL scheme http+docker
...
docker.errors.DockerException: Error while fetching server API version: Not supported URL scheme http+docker
```

**Comment by ARNAUD-25** [comment]
What is the logic for accurately reproducing the results using our data?

**Comment by Kotrix** [comment]
> What is the logic for accurately reproducing the results using our data?

If you want to run experiments on your own datasets you need to create a preprocessed version of your dataset compatible with the ESA-ADB framework (see scripts for preprocessing in the notebooks folder) in the data/preprocessed folder. Note that preprocessing scripts add a proper data record to data/datasets.csv as well. Then, you can use this dataset by name in scripts like mission1_experiments.py
